services:
  db:
    image: postgres
    container_name: postgres_db
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports: 
      - "${POSTGRES_PORT}:5432"
    volumes: 
      - volume_pgdata:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: always
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - network

  python_app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: app_e_commerce
    restart: always
    depends_on:
      - db
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET_KEY: ${APP_SECRET_KEY}
      API_PORT: ${API_PORT}
    networks:
      - network

volumes:
  volume_pgdata:
  volume_pgadmin:

networks:
  network:
