services: 
  # Service postgres
  db:
    image: postgres
    container_name: postgres_db
    environment: 
      POSTGRES_DB: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    restart: always
    ports: 
      - "5432:5432"
    volumes: 
      - volume_pgdata:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network
  
  # Service pgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_USER: admin
      PGADMIN_DEFAULT_PASSWORD: mdp
    restart: always
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - network

  # Service Python (app)
  python_app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: app_e_commerce
    restart: always
    depends_on:
      - db
    networks:
      - network


# Volumes
volumes:
  volume_pgdata:
  volume_pgadmin:

# RÃ©seaux
networks:
  network: 
